### ISSUE TITLE
Correctly treat smileys with square parentheses at beginning of messages

### ISSUE THREAD

**Issue by marc1706** [nickvergessen/phpbb-tool-trimmessage#6]
See related topic: https://www.phpbb.com/community/viewtopic.php?f=456&t=2259081&start=270#p14029636

I'm able to reproduce this locally. Will push a PR with failing tests.

**Comment by marc1706** [comment]
Maybe increase the version number in order to have it updated when having the version constraints in composer.json?

**Comment by nickvergessen** [comment]
Will wrap a new release this week

**Comment by marc1706** [comment]
Ok, thanks.

**Comment by nickvergessen** [comment]
https://github.com/nickvergessen/phpbb-tool-trimmessage/releases/tag/release-1.3.1

**Comment by marc1706** [comment]
Thx
